<?php

namespace Erico\ApiBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends  PublicationRepository
{
	public function FindActuCat($idcat)
	{
	 
	  $query = $this->_em->createQuery('SELECT a FROM EricoApiBundle:Article a JOIN a.categories c WHERE a.archiver = false AND a.publier = true AND c.id = :idc ORDER BY a.datePublish DESC');
	  $query->setParameter('idc', $idcat);
	  /*$query->setFirstResult($first);
	  $query->setMaxResults($limit);// est l'équivalent de LIMIT en DQL */
      $resultats = $query->getResult();
	  
	  
      return $resultats;  
	}
}
