<?php

namespace Erico\ApiBundle\Entity;

/**
 * DeclinaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeclinaisonRepository extends \Doctrine\ORM\EntityRepository
{
}
