<?php

namespace Erico\ApiBundle\Entity;

/**
 * JurisprudenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JurisprudenceRepository extends TexteRepository
{
	
	public function findAllJuridiction()
	{
	  $query = $this->_em->createQuery('SELECT DISTINCT j.nomTribunal FROM EricoApiBundle:Jurisprudence j  ORDER BY j.nomTribunal ASC');
      $resultats = $query->getResult();
      return $resultats;  
	}
	
	public function findAllSection()
	{
	  $query = $this->_em->createQuery('SELECT DISTINCT j.sectionTribunal FROM EricoApiBundle:Jurisprudence j  ORDER BY j.sectionTribunal ASC');
      $resultats = $query->getResult();
      return $resultats;  
	}
	
	public function FindjurisprudenceCat($idcat)
	{
	 
	  $query = $this->_em->createQuery('SELECT j FROM EricoApiBundle:Jurisprudence j JOIN j.categories c WHERE j.archiver = false AND j.publier = true AND c.id = :idc ORDER BY j.datePublish DESC');
	  $query->setParameter('idc', $idcat);
	  /*$query->setFirstResult($first);
	  $query->setMaxResults($limit);// est l'équivalent de LIMIT en DQL */
      $resultats = $query->getResult();
	  
	  
      return $resultats;  
	}
	
}
