<?php

namespace Erico\ApiBundle\Entity;

/**
 * LoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoiRepository extends \Doctrine\ORM\EntityRepository
{
}
