<?php

namespace Erico\ApiBundle\Entity;

/**
 * ParagrapheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
 
use Erico\ApiBundle\Services\MyService;
 
class ParagrapheRepository extends \Doctrine\ORM\EntityRepository
{
	
	
  
	public function getListeParaTexte($idtext)
	{
		
		 $query = $this->_em->createQuery('SELECT DISTINCT p FROM EricoApiBundle:Paragraphe p WHERE p.texte = :idt ORDER BY p.id ASC');
		  $query->setParameter('idt', $idtext);
		  $resultats = $query->getResult();
		
	}
	
	
	
	public function Search($ch, $pub, $num, $op, $date1, $date2, $juridiction, $section, $nature)
	{
		//etant donné que le conteneur de service n'est pas accessible ici, je suis dans l'obligation d'instancifier ma classe Myservice avant de l'utiliser après avoir utiliser use Erico\ApiBundle\Services\MyService;
		$my_service = new MyService;
		
		$content = 'Paragraphe'; 
		
		$condition = ' WHERE ( p.archiver = false ) ';
		
		if($ch != "")
		{
			
			$exception = $my_service->exceptionkeyword();

			$ch2 = $ch; 
			
			//convertion des caractère spéciaux
			//convertion des caractère spéciaux
			$ch2Special = $my_service->converToSpecialChar($ch2);
			
			$condition .= " AND ( ( p.designation LIKE '%".$ch2."%' OR p.description LIKE '%".$ch2Special."%' )  ";
			
			$tabstr = explode(" ", $ch);
			
			if( count($tabstr)>1 ){
				
				foreach($tabstr as $m)
				{
					
					if( strlen($m) > 2 and !(in_array($m, $exception)))
					{
						
						// mots au début ou fin ou séparé par un signe -,_ ou .
						//$regexp  = '(^|(.+[-|_|.]))'.$m.'(([-|_|.].+)|$)';

						// mots au début ou fin ou séparé par 2 espaces
						//$regexp2 = '(^|.+ )'.$m.'( .+|$)';

						// Recherche dans le dns ET la description (mots evidents)
						//$condition .= " OR ( 'REGEXP(p.designation, ".$regexp2." = true' ) )";
					
						//'REGEXP(x.your_property, :regexp) = true'
						
						//$m = ' '.$m.' ';
						
						//convertion des caractère spéciaux
						$mSpecial = $my_service->converToSpecialChar($m);
						
						$condition .= " OR ( p.designation LIKE '%".$m."%' OR p.description LIKE '%".$mSpecial."%' )"; 
					}
					
				}  
				
			}
			
			$condition .= ' )';
			
			
			
		}
		
		
		//recupération des paragraphes de texte de loi uniquement
		//$condition .= 'AND ( p.texte  IN ( SELECT  t FROM EricoApiBundle:Document t ) )';
		if($pub == "loi")
		{ 
			$condition .= 'AND ( p.texte  IN ( SELECT  t FROM EricoApiBundle:TexteLoi t ) )';
		}
		
		$query = $this->_em->createQuery('SELECT  p FROM EricoApiBundle:'.$content.' p '.$condition);
		
		//mb_convert_encoding(strip_tags ($pub->getDescription()), 'UTF-8', 'HTML-ENTITIES')
		
		//$queryparagraphe = $this->_em->createQuery("SELECT  p FROM EricoApiBundle:Paragraphe p WHERE p.description LIKE '%".$char."%' ");
	  
		//$query = $this->_em->createQuery('SELECT  p FROM EricoApiBundle:Publication p  WHERE p.designation LIKE \'%'.$char.'%\' or p.description LIKE \'%'.$char.'%\'');
     
		$resultats = $query->getResult();

		return $resultats;  
				
	}
	
}
