<?php

namespace Erico\ApiBundle\Entity;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends  PublicationRepository
{
	
	public function FindPubCat($idcat)
	{
	 
	  $query = $this->_em->createQuery('SELECT p FROM EricoApiBundle:Produit p JOIN p.categories c WHERE p.archiver = false AND p.publier = true AND c.id = :idc ORDER BY p.id DESC');
	  $query->setParameter('idc', $idcat);
	  /*$query->setFirstResult($first);
	  $query->setMaxResults($limit);// est l'équivalent de LIMIT en DQL */
      $resultats = $query->getResult();
	  
	  
      return $resultats;  
	}
	
}
