<?php

namespace Erico\ApiBundle\Entity;

/**
 * TexteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TexteRepository extends  PublicationRepository
{
	
	
	
	
	public function FindtextCat($idcat)
	{
	 
	  $query = $this->_em->createQuery('SELECT t FROM EricoApiBundle:Texte t JOIN t.categories c WHERE t.archiver = false AND t.publier = true AND c.id = :idc ORDER BY t.datePublish DESC');
	  $query->setParameter('idc', $idcat);
	  /*$query->setFirstResult($first);
	  $query->setMaxResults($limit);// est l'équivalent de LIMIT en DQL */
      $resultats = $query->getResult();
	  
	  
      return $resultats;  
	}
	
	
}
