<?php

namespace Erico\ApiBundle\Entity;

/**
 * TexteLoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TexteLoiRepository extends TexteRepository
{
	
	
}
